package com.chervon.iot.mobile.model;

import org.springframework.stereotype.Component;

import java.util.Date;
@Component
public class Mobile_Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.request_start_time
     *
     * @mbggenerated
     */
    private Date requestStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.bean_name
     *
     * @mbggenerated
     */
    private String beanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.session_id
     *
     * @mbggenerated
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.repost_status
     *
     * @mbggenerated
     */
    private String repostStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.params
     *
     * @mbggenerated
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.method_name
     *
     * @mbggenerated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.duration
     *
     * @mbggenerated
     */
    private Long duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.end_point
     *
     * @mbggenerated
     */
    private String endPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.response_json
     *
     * @mbggenerated
     */
    private Object responseJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.user_email
     *
     * @mbggenerated
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.remote_address
     *
     * @mbggenerated
     */
    private String remoteAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_log.request_method
     *
     * @mbggenerated
     */
    private String requestMethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.request_start_time
     *
     * @return the value of mobile_log.request_start_time
     *
     * @mbggenerated
     */
    public Date getRequestStartTime() {
        return requestStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.request_start_time
     *
     * @param requestStartTime the value for mobile_log.request_start_time
     *
     * @mbggenerated
     */
    public void setRequestStartTime(Date requestStartTime) {
        this.requestStartTime = requestStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.bean_name
     *
     * @return the value of mobile_log.bean_name
     *
     * @mbggenerated
     */
    public String getBeanName() {
        return beanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.bean_name
     *
     * @param beanName the value for mobile_log.bean_name
     *
     * @mbggenerated
     */
    public void setBeanName(String beanName) {
        this.beanName = beanName == null ? null : beanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.session_id
     *
     * @return the value of mobile_log.session_id
     *
     * @mbggenerated
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.session_id
     *
     * @param sessionId the value for mobile_log.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.repost_status
     *
     * @return the value of mobile_log.repost_status
     *
     * @mbggenerated
     */
    public String getRepostStatus() {
        return repostStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.repost_status
     *
     * @param repostStatus the value for mobile_log.repost_status
     *
     * @mbggenerated
     */
    public void setRepostStatus(String repostStatus) {
        this.repostStatus = repostStatus == null ? null : repostStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.params
     *
     * @return the value of mobile_log.params
     *
     * @mbggenerated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.params
     *
     * @param params the value for mobile_log.params
     *
     * @mbggenerated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.method_name
     *
     * @return the value of mobile_log.method_name
     *
     * @mbggenerated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.method_name
     *
     * @param methodName the value for mobile_log.method_name
     *
     * @mbggenerated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.id
     *
     * @return the value of mobile_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.id
     *
     * @param id the value for mobile_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.duration
     *
     * @return the value of mobile_log.duration
     *
     * @mbggenerated
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.duration
     *
     * @param duration the value for mobile_log.duration
     *
     * @mbggenerated
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.end_point
     *
     * @return the value of mobile_log.end_point
     *
     * @mbggenerated
     */
    public String getEndPoint() {
        return endPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.end_point
     *
     * @param endPoint the value for mobile_log.end_point
     *
     * @mbggenerated
     */
    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint == null ? null : endPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.response_json
     *
     * @return the value of mobile_log.response_json
     *
     * @mbggenerated
     */
    public Object getResponseJson() {
        return responseJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.response_json
     *
     * @param responseJson the value for mobile_log.response_json
     *
     * @mbggenerated
     */
    public void setResponseJson(Object responseJson) {
        this.responseJson = responseJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.user_email
     *
     * @return the value of mobile_log.user_email
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.user_email
     *
     * @param userEmail the value for mobile_log.user_email
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.remote_address
     *
     * @return the value of mobile_log.remote_address
     *
     * @mbggenerated
     */
    public String getRemoteAddress() {
        return remoteAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.remote_address
     *
     * @param remoteAddress the value for mobile_log.remote_address
     *
     * @mbggenerated
     */
    public void setRemoteAddress(String remoteAddress) {
        this.remoteAddress = remoteAddress == null ? null : remoteAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_log.request_method
     *
     * @return the value of mobile_log.request_method
     *
     * @mbggenerated
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_log.request_method
     *
     * @param requestMethod the value for mobile_log.request_method
     *
     * @mbggenerated
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod == null ? null : requestMethod.trim();
    }
}