package com.chervon.iot.mobile.model;

import java.util.Date;

public class Mobile_ErrorLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_errorlog.requestTime
     *
     * @mbggenerated
     */
    private Date requesttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_errorlog.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_errorlog.exception
     *
     * @mbggenerated
     */
    private String exception;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_errorlog.requestJson
     *
     * @mbggenerated
     */
    private Object requestjson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_errorlog.repostStatus
     *
     * @mbggenerated
     */
    private String repoststatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_errorlog.Re-RostTimes
     *
     * @mbggenerated
     */
    private Integer reRosttimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_errorlog.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_errorlog.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_errorlog.requestTime
     *
     * @return the value of mobile_errorlog.requestTime
     *
     * @mbggenerated
     */
    public Date getRequesttime() {
        return requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_errorlog.requestTime
     *
     * @param requesttime the value for mobile_errorlog.requestTime
     *
     * @mbggenerated
     */
    public void setRequesttime(Date requesttime) {
        this.requesttime = requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_errorlog.level
     *
     * @return the value of mobile_errorlog.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_errorlog.level
     *
     * @param level the value for mobile_errorlog.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_errorlog.exception
     *
     * @return the value of mobile_errorlog.exception
     *
     * @mbggenerated
     */
    public String getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_errorlog.exception
     *
     * @param exception the value for mobile_errorlog.exception
     *
     * @mbggenerated
     */
    public void setException(String exception) {
        this.exception = exception == null ? null : exception.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_errorlog.requestJson
     *
     * @return the value of mobile_errorlog.requestJson
     *
     * @mbggenerated
     */
    public Object getRequestjson() {
        return requestjson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_errorlog.requestJson
     *
     * @param requestjson the value for mobile_errorlog.requestJson
     *
     * @mbggenerated
     */
    public void setRequestjson(Object requestjson) {
        this.requestjson = requestjson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_errorlog.repostStatus
     *
     * @return the value of mobile_errorlog.repostStatus
     *
     * @mbggenerated
     */
    public String getRepoststatus() {
        return repoststatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_errorlog.repostStatus
     *
     * @param repoststatus the value for mobile_errorlog.repostStatus
     *
     * @mbggenerated
     */
    public void setRepoststatus(String repoststatus) {
        this.repoststatus = repoststatus == null ? null : repoststatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_errorlog.Re-RostTimes
     *
     * @return the value of mobile_errorlog.Re-RostTimes
     *
     * @mbggenerated
     */
    public Integer getReRosttimes() {
        return reRosttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_errorlog.Re-RostTimes
     *
     * @param reRosttimes the value for mobile_errorlog.Re-RostTimes
     *
     * @mbggenerated
     */
    public void setReRosttimes(Integer reRosttimes) {
        this.reRosttimes = reRosttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_errorlog.type
     *
     * @return the value of mobile_errorlog.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_errorlog.type
     *
     * @param type the value for mobile_errorlog.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_errorlog.id
     *
     * @return the value of mobile_errorlog.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_errorlog.id
     *
     * @param id the value for mobile_errorlog.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }
}