package com.chervon.iot.mobile.model;

import java.util.Date;

public class Mobile_Knowledges {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_knowledges.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_knowledges.body
     *
     * @mbggenerated
     */
    private Object body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_knowledges.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_knowledges.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_knowledges.pageNumber
     *
     * @mbggenerated
     */
    private Integer pagenumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_knowledges.id
     *
     * @return the value of mobile_knowledges.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_knowledges.id
     *
     * @param id the value for mobile_knowledges.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_knowledges.body
     *
     * @return the value of mobile_knowledges.body
     *
     * @mbggenerated
     */
    public Object getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_knowledges.body
     *
     * @param body the value for mobile_knowledges.body
     *
     * @mbggenerated
     */
    public void setBody(Object body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_knowledges.type
     *
     * @return the value of mobile_knowledges.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_knowledges.type
     *
     * @param type the value for mobile_knowledges.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_knowledges.updateTime
     *
     * @return the value of mobile_knowledges.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_knowledges.updateTime
     *
     * @param updatetime the value for mobile_knowledges.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_knowledges.pageNumber
     *
     * @return the value of mobile_knowledges.pageNumber
     *
     * @mbggenerated
     */
    public Integer getPagenumber() {
        return pagenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_knowledges.pageNumber
     *
     * @param pagenumber the value for mobile_knowledges.pageNumber
     *
     * @mbggenerated
     */
    public void setPagenumber(Integer pagenumber) {
        this.pagenumber = pagenumber;
    }
}