package com.chervon.iot.mobile.model;

import java.util.Date;

public class Mobile_UserActionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_useractionlog.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_useractionlog.user
     *
     * @mbggenerated
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_useractionlog.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_useractionlog.operatedtime
     *
     * @mbggenerated
     */
    private Date operatedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_useractionlog.requestion
     *
     * @mbggenerated
     */
    private Object requestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_useractionlog.responseJson
     *
     * @mbggenerated
     */
    private Object responsejson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_useractionlog.id
     *
     * @return the value of mobile_useractionlog.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_useractionlog.id
     *
     * @param id the value for mobile_useractionlog.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_useractionlog.user
     *
     * @return the value of mobile_useractionlog.user
     *
     * @mbggenerated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_useractionlog.user
     *
     * @param user the value for mobile_useractionlog.user
     *
     * @mbggenerated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_useractionlog.type
     *
     * @return the value of mobile_useractionlog.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_useractionlog.type
     *
     * @param type the value for mobile_useractionlog.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_useractionlog.operatedtime
     *
     * @return the value of mobile_useractionlog.operatedtime
     *
     * @mbggenerated
     */
    public Date getOperatedtime() {
        return operatedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_useractionlog.operatedtime
     *
     * @param operatedtime the value for mobile_useractionlog.operatedtime
     *
     * @mbggenerated
     */
    public void setOperatedtime(Date operatedtime) {
        this.operatedtime = operatedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_useractionlog.requestion
     *
     * @return the value of mobile_useractionlog.requestion
     *
     * @mbggenerated
     */
    public Object getRequestion() {
        return requestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_useractionlog.requestion
     *
     * @param requestion the value for mobile_useractionlog.requestion
     *
     * @mbggenerated
     */
    public void setRequestion(Object requestion) {
        this.requestion = requestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_useractionlog.responseJson
     *
     * @return the value of mobile_useractionlog.responseJson
     *
     * @mbggenerated
     */
    public Object getResponsejson() {
        return responsejson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_useractionlog.responseJson
     *
     * @param responsejson the value for mobile_useractionlog.responseJson
     *
     * @mbggenerated
     */
    public void setResponsejson(Object responsejson) {
        this.responsejson = responsejson;
    }
}