package com.chervon.iot.mobile.model;

import java.math.BigDecimal;

public class Mobile_user {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.sfid
     *
     * @mbggenerated
     */
    private String sfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.id
     *
     * @return the value of mobile_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.id
     *
     * @param id the value for mobile_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.nickname
     *
     * @return the value of mobile_user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.nickname
     *
     * @param nickname the value for mobile_user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.email
     *
     * @return the value of mobile_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.email
     *
     * @param email the value for mobile_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.password
     *
     * @return the value of mobile_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.password
     *
     * @param password the value for mobile_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.sfid
     *
     * @return the value of mobile_user.sfid
     *
     * @mbggenerated
     */
    public String getSfid() {
        return sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.sfid
     *
     * @param sfid the value for mobile_user.sfid
     *
     * @mbggenerated
     */
    public void setSfid(String sfid) {
        this.sfid = sfid == null ? null : sfid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.longitude
     *
     * @return the value of mobile_user.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.longitude
     *
     * @param longitude the value for mobile_user.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.latitude
     *
     * @return the value of mobile_user.latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.latitude
     *
     * @param latitude the value for mobile_user.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
}