package com.chervon.iot.mobile.model;

import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.Date;
@Component
public class Mobile_User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.sfdc_id
     *
     * @mbggenerated
     */
    private String sfdcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.photourl
     *
     * @mbggenerated
     */
    private String photourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.lastpasswordresetdate
     *
     * @mbggenerated
     */
    private Date lastpasswordresetdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.role
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_user.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.id
     *
     * @return the value of mobile_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.id
     *
     * @param id the value for mobile_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.username
     *
     * @return the value of mobile_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.username
     *
     * @param username the value for mobile_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.password
     *
     * @return the value of mobile_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.password
     *
     * @param password the value for mobile_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.sfdc_id
     *
     * @return the value of mobile_user.sfdc_id
     *
     * @mbggenerated
     */
    public String getSfdcId() {
        return sfdcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.sfdc_id
     *
     * @param sfdcId the value for mobile_user.sfdc_id
     *
     * @mbggenerated
     */
    public void setSfdcId(String sfdcId) {
        this.sfdcId = sfdcId == null ? null : sfdcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.longitude
     *
     * @return the value of mobile_user.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.longitude
     *
     * @param longitude the value for mobile_user.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.latitude
     *
     * @return the value of mobile_user.latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.latitude
     *
     * @param latitude the value for mobile_user.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.photourl
     *
     * @return the value of mobile_user.photourl
     *
     * @mbggenerated
     */
    public String getPhotourl() {
        return photourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.photourl
     *
     * @param photourl the value for mobile_user.photourl
     *
     * @mbggenerated
     */
    public void setPhotourl(String photourl) {
        this.photourl = photourl == null ? null : photourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.name
     *
     * @return the value of mobile_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.name
     *
     * @param name the value for mobile_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.lastpasswordresetdate
     *
     * @return the value of mobile_user.lastpasswordresetdate
     *
     * @mbggenerated
     */
    public Date getLastpasswordresetdate() {
        return lastpasswordresetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.lastpasswordresetdate
     *
     * @param lastpasswordresetdate the value for mobile_user.lastpasswordresetdate
     *
     * @mbggenerated
     */
    public void setLastpasswordresetdate(Date lastpasswordresetdate) {
        this.lastpasswordresetdate = lastpasswordresetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.enabled
     *
     * @return the value of mobile_user.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.enabled
     *
     * @param enabled the value for mobile_user.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.email
     *
     * @return the value of mobile_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.email
     *
     * @param email the value for mobile_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.role
     *
     * @return the value of mobile_user.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.role
     *
     * @param role the value for mobile_user.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_user.createdate
     *
     * @return the value of mobile_user.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_user.createdate
     *
     * @param createdate the value for mobile_user.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}