package com.chervon.iot.mobile.model;

import java.util.Date;

public class Mobile_JWT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_jwt.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_jwt.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_jwt.jwt
     *
     * @mbggenerated
     */
    private String jwt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_jwt.effectTime
     *
     * @mbggenerated
     */
    private Date effecttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_jwt.expirationTime
     *
     * @mbggenerated
     */
    private Date expirationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_jwt.isDelete
     *
     * @mbggenerated
     */
    private Boolean isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_jwt.expirationType
     *
     * @mbggenerated
     */
    private String expirationtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_jwt.id
     *
     * @return the value of mobile_jwt.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_jwt.id
     *
     * @param id the value for mobile_jwt.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_jwt.userName
     *
     * @return the value of mobile_jwt.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_jwt.userName
     *
     * @param username the value for mobile_jwt.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_jwt.jwt
     *
     * @return the value of mobile_jwt.jwt
     *
     * @mbggenerated
     */
    public String getJwt() {
        return jwt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_jwt.jwt
     *
     * @param jwt the value for mobile_jwt.jwt
     *
     * @mbggenerated
     */
    public void setJwt(String jwt) {
        this.jwt = jwt == null ? null : jwt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_jwt.effectTime
     *
     * @return the value of mobile_jwt.effectTime
     *
     * @mbggenerated
     */
    public Date getEffecttime() {
        return effecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_jwt.effectTime
     *
     * @param effecttime the value for mobile_jwt.effectTime
     *
     * @mbggenerated
     */
    public void setEffecttime(Date effecttime) {
        this.effecttime = effecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_jwt.expirationTime
     *
     * @return the value of mobile_jwt.expirationTime
     *
     * @mbggenerated
     */
    public Date getExpirationtime() {
        return expirationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_jwt.expirationTime
     *
     * @param expirationtime the value for mobile_jwt.expirationTime
     *
     * @mbggenerated
     */
    public void setExpirationtime(Date expirationtime) {
        this.expirationtime = expirationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_jwt.isDelete
     *
     * @return the value of mobile_jwt.isDelete
     *
     * @mbggenerated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_jwt.isDelete
     *
     * @param isdelete the value for mobile_jwt.isDelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_jwt.expirationType
     *
     * @return the value of mobile_jwt.expirationType
     *
     * @mbggenerated
     */
    public String getExpirationtype() {
        return expirationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_jwt.expirationType
     *
     * @param expirationtype the value for mobile_jwt.expirationType
     *
     * @mbggenerated
     */
    public void setExpirationtype(String expirationtype) {
        this.expirationtype = expirationtype == null ? null : expirationtype.trim();
    }
}