package com.chervon.iot.mobile.model;

import java.math.BigDecimal;
import java.util.Date;

public class Mobile_Weather {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_weather.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_weather.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_weather.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_weather.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_weather.weatherJson
     *
     * @mbggenerated
     */
    private Object weatherjson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_weather.id
     *
     * @return the value of mobile_weather.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_weather.id
     *
     * @param id the value for mobile_weather.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_weather.updateTime
     *
     * @return the value of mobile_weather.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_weather.updateTime
     *
     * @param updatetime the value for mobile_weather.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_weather.longitude
     *
     * @return the value of mobile_weather.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_weather.longitude
     *
     * @param longitude the value for mobile_weather.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_weather.latitude
     *
     * @return the value of mobile_weather.latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_weather.latitude
     *
     * @param latitude the value for mobile_weather.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_weather.weatherJson
     *
     * @return the value of mobile_weather.weatherJson
     *
     * @mbggenerated
     */
    public Object getWeatherjson() {
        return weatherjson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_weather.weatherJson
     *
     * @param weatherjson the value for mobile_weather.weatherJson
     *
     * @mbggenerated
     */
    public void setWeatherjson(Object weatherjson) {
        this.weatherjson = weatherjson;
    }
}