package com.chervon.iot.mobile.model;

public class Mobile_Categories {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_categories.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_categories.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_categories.categorieid
     *
     * @mbggenerated
     */
    private String categorieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_categories.photo_url
     *
     * @mbggenerated
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_categories.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_categories.isDelete
     *
     * @mbggenerated
     */
    private String isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_categories.id
     *
     * @return the value of mobile_categories.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_categories.id
     *
     * @param id the value for mobile_categories.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_categories.name
     *
     * @return the value of mobile_categories.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_categories.name
     *
     * @param name the value for mobile_categories.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_categories.categorieid
     *
     * @return the value of mobile_categories.categorieid
     *
     * @mbggenerated
     */
    public String getCategorieid() {
        return categorieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_categories.categorieid
     *
     * @param categorieid the value for mobile_categories.categorieid
     *
     * @mbggenerated
     */
    public void setCategorieid(String categorieid) {
        this.categorieid = categorieid == null ? null : categorieid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_categories.photo_url
     *
     * @return the value of mobile_categories.photo_url
     *
     * @mbggenerated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_categories.photo_url
     *
     * @param photoUrl the value for mobile_categories.photo_url
     *
     * @mbggenerated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_categories.description
     *
     * @return the value of mobile_categories.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_categories.description
     *
     * @param description the value for mobile_categories.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_categories.isDelete
     *
     * @return the value of mobile_categories.isDelete
     *
     * @mbggenerated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_categories.isDelete
     *
     * @param isdelete the value for mobile_categories.isDelete
     *
     * @mbggenerated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }
}