package com.chervon.iot.mobile.mapper;

import com.chervon.iot.mobile.model.Mobile_Categories;

public interface Mobile_CategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_categories
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_categories
     *
     * @mbggenerated
     */
    int insert(Mobile_Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_categories
     *
     * @mbggenerated
     */
    int insertSelective(Mobile_Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_categories
     *
     * @mbggenerated
     */
    Mobile_Categories selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_categories
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mobile_Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_categories
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mobile_Categories record);
}