package com.chervon.iot.mobile.mapper;

import com.chervon.iot.mobile.model.Mobile_Knowledges;

public interface Mobile_KnowledgesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_knowledges
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_knowledges
     *
     * @mbggenerated
     */
    int insert(Mobile_Knowledges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_knowledges
     *
     * @mbggenerated
     */
    int insertSelective(Mobile_Knowledges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_knowledges
     *
     * @mbggenerated
     */
    Mobile_Knowledges selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_knowledges
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mobile_Knowledges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_knowledges
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mobile_Knowledges record);
}