package com.chervon.iot.mobile.mapper;

import com.chervon.iot.mobile.model.Mobile_user;

public interface Mobile_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int insert(Mobile_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int insertSelective(Mobile_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    Mobile_user selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mobile_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mobile_user record);
}