package com.chervon.iot.mobile.mapper;

import com.chervon.iot.mobile.model.Mobile_ErrorLog;

public interface Mobile_ErrorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_errorlog
     *
     * @mbggenerated
     */
    int insert(Mobile_ErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_errorlog
     *
     * @mbggenerated
     */
    int insertSelective(Mobile_ErrorLog record);
}