package com.chervon.iot.mobile.mapper;

import com.chervon.iot.mobile.model.Mobile_User;

public interface Mobile_UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int insert(Mobile_User record);
    Mobile_User getUserByEmail(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int insertSelective(Mobile_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    Mobile_User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mobile_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mobile_User record);
}