package com.chervon.iot.mobile.mapper;

import com.chervon.iot.mobile.model.Mobile_Weather;

public interface Mobile_WeatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_weather
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_weather
     *
     * @mbggenerated
     */
    int insert(Mobile_Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_weather
     *
     * @mbggenerated
     */
    int insertSelective(Mobile_Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_weather
     *
     * @mbggenerated
     */
    Mobile_Weather selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_weather
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mobile_Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_weather
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mobile_Weather record);
}