package com.chervon.iot.mobile.mapper;

import com.chervon.iot.mobile.model.Mobile_JWT;

public interface Mobile_JWTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_jwt
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_jwt
     *
     * @mbggenerated
     */
    int insert(Mobile_JWT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_jwt
     *
     * @mbggenerated
     */
    int insertSelective(Mobile_JWT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_jwt
     *
     * @mbggenerated
     */
    Mobile_JWT selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_jwt
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mobile_JWT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_jwt
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mobile_JWT record);
}